title: REV_UWU_GANG layer
author:
  name: Asatistic
  email: ¯\_(ツ)_/¯
  
description: >
  A weeb reverser, exploring weird things.

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  date_format: "%b %-d, %Y"
  social_links: 
      - { platform: github,         user_url: "https://github.com/NtQuerySystemInformation" }
      - { platform: twitter,        user_url: "https://twitter.com/kasua02" } 

# If you want to link only specific pages in your header, uncomment this and add the path to the pages in
# order as they should show up.
#
# header_pages:
#   - about.md

# Set to `true` to show excerpts on the homepage.
#
# show_excerpts: false
