title: A weeb reverser layer.
author:
  name: Asatistic
  email: ¯\_(ツ)_/¯
  
description: >
  A weeb reverser, exploring weird things for fun.

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  date_format: "%b %-d, %Y"
  social_links: 
      - { platform: github,         user_url: "https://github.com/NtQuerySystemInformation" }
      - { platform: twitter,        user_url: "https://twitter.com/kasua02" } 

header_pages:
   - about.md

# Set to `true` to show excerpts on the homepage.
#
# show_excerpts: false
